#
# Description: Build OpenWrt using GitHub Actions
#
name: Build OpenWrt

on:
  workflow_dispatch:
    inputs:
      model:
        description: 选择需要编译固件的路由器型号
        required: true
        default: 'r4a'
        type: choice
        options:
        - r4a
        - r3
        - hc5611

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  #FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ${{ inputs.model }}.config
  DIY_P1_SH: ${{ inputs.model }}-diy-part1.sh
  DIY_P2_SH: ${{ inputs.model }}-diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  ROUTER_MODEL: $ROUTER_MODEL

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04

    steps:    
      - name: Router model
        id: router
        run: |
          echo "${{ inputs.model }}"
          if [ "${{ inputs.model }}" == "r4a" ]; then
          echo "ROUTER_MODEL=Xiaomi Mi Router 4A Gigabit Edition" >> $GITHUB_ENV
          elif [ "${{ inputs.model }}" == "r3" ]; then
          echo "ROUTER_MODEL=Xiaomi Mi Router 3" >> $GITHUB_ENV
          else
          echo "ROUTER_MODEL=HiWiFi HC5611" >> $GITHUB_ENV
          fi        
     
      - name: Show Prepare information
        run: |
          echo $ROUTER_MODEL
          cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
            ## Sources
            Time: $(date +"%Y-%m-%d %H:%M %A")
            Router Model: ${{env.ROUTER_MODEL }}
            Config: $CONFIG_FILE
            Openwrt: $REPO_URL
            Upload Firware: $UPLOAD_FIRMWARE
            Upload Release: $UPLOAD_RELEASE
          EOF

  build:
    name: Build $ROUTER_MODEL
    
    needs: prepare
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 清理Docker镜像和软件包
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php* mongodb* dotnet* moby* snapd* || true

    - name: 安装依赖软件包
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        echo "---------install依赖包-------------"
        sudo -E apt-get -y install $(cat $GITHUB_WORKSPACE/depends-ubuntu)
        echo "---------dist-upgrade--------------"
        sudo -E apt-get -y dist-upgrade

    - name: 清理空间
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: 设置时区和工作目录
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        echo "SPACE_A=$(df / | grep '/' | awk '{print $4}')" >> $GITHUB_ENV
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: Load custom feeds
      run: |
        #[ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        #[ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Download package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Check space usage
      if: (!cancelled())
      run: |
        cd openwrt
        echo "SPACE_B=$(df / | grep '/' | awk '{print $4}')" >> $GITHUB_ENV
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Show build information
      run: |
        cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
          ## Firmware Information
          路 由 器: ${{ env.ROUTER_MODEL }}
          使用空间: $(echo $[($SPACE_A-$SPACE_B) / 102400])G
          文件时间: $FILE_DATE
          设备名称: $DEVICE_NAME
          固件目录: $FIRMWARE
          配置文件: $CONFIG_FILE
          修改脚本: $DIY_P1_SH $DIY_P2_SH
          Version Info: cat ${{ env.FIRMWARE }}/version.buildinfo
        EOF
        
    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
      run: |
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")${{ env.DEVICE_NAME }}" >> $GITHUB_OUTPUT
        touch release.txt
        echo "OpenWrt for ${{ env.ROUTER_MODEL }}" >> release.txt
        cat ${{ env.FIRMWARE }}/version.buildinfo >> release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

  delete:
    name: Delete old workflow
    needs: [ prepare, build ]
    runs-on: ubuntu-22.04
    
    steps:
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 2

    - name: Delete old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 5
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
