#
# Description: Build OpenWrt using GitHub Actions
#
name: Model

on:
  workflow_dispatch:
    inputs:
      model:
        description: 选择需要编译固件的路由器型号
        required: true
        default: 'r4a'
        type: choice
        options:
        - r4a
        - r3
        - hc5611
        
env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  #FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ${{ inputs.model }}.config
  DIY_P1_SH: ${{ inputs.model }}-diy-part1.sh
  DIY_P2_SH: ${{ inputs.model }}-diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
   
    outputs:
      ROUTER_MODEL: ${{ steps.router.outputs.ROUTER_MODEL }}
    
    steps:
    - name: Router model
      id: router
      run: |
        if [ "${{ inputs.model }}" == "r4a" ]; then
        echo "ROUTER_MODEL=Xiaomi Mi Router 4A Gigabit Edition" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.model }}" == "r3" ]; then
        echo "ROUTER_MODEL=Xiaomi Mi Router 3" >> $GITHUB_OUTPUT
        else
        echo "ROUTER_MODEL=HiWiFi HC5611" >> $GITHUB_OUTPUT
        fi
     
    - name: Show Prepare information
      run: |
        cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
          ## Sources
          Time: $(date +"%Y-%m-%d %H:%M %A")
          Router Model: ${{env.ROUTER_MODEL }}
          Config: $CONFIG_FILE
          Openwrt: $REPO_URL
          Upload Firware: $UPLOAD_FIRMWARE
          Upload Release: $UPLOAD_RELEASE
        EOF

  build:
    name: Build ${{ needs.prepare.outputs.ROUTER_MODEL }} Firmware
    needs: prepare
    runs-on: ubuntu-22.04
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check space usage
      if: (!cancelled())
      run: |
        cd openwrt
        echo "SPACE_B=$(df / | grep '/' | awk '{print $4}')" >> $GITHUB_ENV

    - name: Show build information
      run: |
        cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
          ## Firmware Information
          路 由 器: ${{ needs.prepare.outputs.ROUTER_MODEL }}
          路 由 器: $ROUTER_MODEL
          使用空间: $(echo $[($SPACE_A-$SPACE_B) / 1024000])G
          配置文件: $CONFIG_FILE
          修改脚本: $DIY_P1_SH $DIY_P2_SH
          Version Info: $(cat ${{ env.FIRMWARE }}/version.buildinfo)
        EOF
