
#
# Description: Build OpenWrt using GitHub Actions
#
name: Model test

on:
  workflow_dispatch:
    inputs:
      model:
        description: 选择需要编译固件的路由器型号
        required: true
        default: 'r4a'
        type: choice
        options:
        - r4a
        - r3
        - hc5611

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  #FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: ${{ inputs.model }}.config
  DIY_P1_SH: ${{ inputs.model }}-diy-part1.sh
  DIY_P2_SH: ${{ inputs.model }}-diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04

    steps:    
      - name: Show r4a information
        
        run: |
          echo "${{ inputs.model }}"
          if [ "${{ inputs.model }}" == "r4a" ]; then
          echo "ROUTER_MODEL=Xiaomi Mi Router 4A Gigabit Edition" >> $GITHUB_ENV
          elif [ "${{ inputs.model }}" == "r3" ]; then
          echo "ROUTER_MODEL=Xiaomi Mi Router 3" >> $GITHUB_ENV
          else
          echo "ROUTER_MODEL=HiWiFi HC5611" >> $GITHUB_ENV
          fi
     
      - name: Show information
        run: |
          echo ${{ env.ROUTER_MODEL }}
          cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
            ## Sources
            Time: $(date +"%Y-%m-%d %H:%M %A")
            Router Model: $ROUTER_MODEL
            Config: $CONFIG_FILE
            Openwrt: $REPO_URL
            Upload Firware: $UPLOAD_FIRMWARE
            Upload Release: $UPLOAD_RELEASE
          EOF
