name: Build Test

on:
  workflow_dispatch
  
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    
    steps:
    - name: Set Timezone
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        
    - name: Space
      run: |
        df -h /
        cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
          #### Sources
          Time: $(date +"%Y-%m-%d %H:%M %A")
          Space Info:
          $(df -h / | awk '{print $2}' | tr "\n" ":" | sed -e 's/:$/\n/') $(df -h / | awk '{print $3}' | tr "\n" ":" | sed -e 's/:$/\n/')  $(df -h / | awk '{print $4}' | tr "\n" ":"|sed -e 's/:$/\n/') 
        EOF
    - name: checkout
      uses: actions/checkout@v3       
      
    - name: Space A
      run: |
        df -h
        echo "SPACE_A=$(df / | grep '/' | awk '{print $4}')" >> $GITHUB_ENV
    
    - name: Space B
      run: |
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
        echo "SPACE_B=$(df / | grep '/' | awk '{print $4}')" >> $GITHUB_ENV
   
    - name: Show information
      run: |
        df -h
        cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
          #### Firmware Information
          Time: $(date +"%Y-%m-%d %H:%M %A")
          #Build Used: $(echo $[($SPACE_A-$SPACE_B) / 1024000])G
          Build Used: $(echo "scale=2;($SPACE_A-$SPACE_B)/1024000" | bc)G
          Space: $(df -h / | awk '{print $2}' | tr "\n" ":" | sed -e 's/:$/\n/') $(df -h / | awk '{print $3}' | tr "\n" ":" | sed -e 's/:$/\n/')  $(df -h / | awk '{print $4}' | tr "\n" ":"|sed -e 's/:$/\n/')
        EOF
