name: Build Test

on:
  workflow_dispatch
  
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    
    steps:
    - name: Space
      run: |
        df -h /
        cat <<EOF | sed -E 's/^  //' >> $GITHUB_STEP_SUMMARY
          #### Sources
          Time: $(date +"%Y-%m-%d %H:%M %A")
          Space Info:
          $(df -h / | awk '{print $2}' | tr "\n" ":" | sed -e 's/:$/\n/') $(df -h / | awk '{print $3}' | tr "\n" ":" | sed -e 's/:$/\n/')  $(df -h / | awk '{print $4}' | tr "\n" ":"|sed -e 's/:$/\n/') 
        EOF
